version: '3.8'

services:
  confirm-ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - confirm-network

networks:
  confirm-network:
    driver: bridge
